/**
 * Shared Bloomberg field definitions used by playground.html and formula-builder.html.
 * Each category: [name, [[mnemonic, description, apiAvailable], ...]]
 */
const XL_FIELDS = [
  // Price & Market Data
  ['Price & Market Data', [
    ['PX_LAST',            'Last price',                             true],
    ['PX_BID',             'Bid price',                             true],
    ['PX_ASK',             'Ask price',                             true],
    ['PX_OPEN',            'Open price',                            true],
    ['PX_HIGH',            'High price',                            true],
    ['PX_LOW',             'Low price',                             true],
    ['PX_VOLUME',          'Volume',                                true],
    ['CHG_PCT_1D',         '1-day % change',                        true],
    ['VWAP',               'Volume-weighted avg price',             false],
    ['PX_MID',             'Mid price',                             true],
    ['TOT_RETURN_INDEX_GROSS_DVDS', 'Total return index (gross divs)', true],
  ]],
  // Fundamentals
  ['Fundamentals', [
    ['SALES_REV_TURN',     'Revenue / Sales',                       true],
    ['EBITDA',             'EBITDA',                                true],
    ['NET_INCOME',         'Net income',                            true],
    ['IS_EPS_DILUTED',     'Diluted EPS',                           true],
    ['MARKET_CAP',         'Market capitalisation',                 true],
    ['CURR_ENTP_VAL',      'Enterprise value',                      true],
    ['PE_RATIO',           'Price / Earnings',                      true],
    ['PX_TO_BOOK_RATIO',   'Price / Book',                          true],
    ['CURRENT_EV_TO_EBITDA','EV / EBITDA',                         true],
    ['RETURN_ON_EQY',      'Return on equity',                      true],
    ['NET_MARGIN',         'Net profit margin',                     true],
    ['FREE_CASH_FLOW',     'Free cash flow',                        true],
    ['BS_TOT_ASSET',       'Total assets',                          true],
    ['TOT_EQUITY',         'Total equity',                          true],
    ['CF_CASH_FROM_OPER',  'Cash from operations',                  true],
  ]],
  // Consensus Estimates (BEst — often Excel-only)
  ['Consensus Estimates (BEst)', [
    ['BEST_EPS',            'BEst consensus EPS',                   false],
    ['BEST_SALES',          'BEst consensus revenue',               false],
    ['BEST_EBITDA',         'BEst consensus EBITDA',                false],
    ['BEST_TARGET_PRICE',   'Analyst consensus price target',       false],
    ['BEST_BUY_CNT',        'Buy recommendations count',            false],
    ['BEST_HOLD_CNT',       'Hold recommendations count',           false],
    ['BEST_SELL_CNT',       'Sell recommendations count',           false],
    ['EARN_SURP_PCT_LAST_QTR','Earnings surprise % last quarter',   false],
    ['BEST_PE_RATIO',       'Forward P/E (BEst)',                   false],
    ['BEST_ROE',            'Forward ROE (BEst)',                   false],
  ]],
  // BVAL / Fixed Income Analytics (often Excel-only)
  ['Fixed Income & BVAL', [
    ['YLD_YTM_MID',        'Yield to maturity (mid)',               true],
    ['DUR_MID',            'Modified duration (mid)',               true],
    ['CONVEXITY_MID',      'Convexity (mid)',                       true],
    ['Z_SPRD_MID',         'Z-spread (mid)',                        false],
    ['OAS_SPREAD_MID',     'OAS spread (mid)',                      false],
    ['BVAL_PRICE_MIDPOINT','BVAL mid price',                        false],
    ['BVAL_PRICE_BID',     'BVAL bid price',                        false],
    ['BVAL_PRICE_ASK',     'BVAL ask price',                        false],
    ['BVAL_SCORE',         'BVAL confidence score (1–10)',          false],
    ['INT_ACC',            'Accrued interest',                      true],
  ]],
  // ESG (Bloomberg ESG scores — Excel-only)
  ['ESG', [
    ['ESG_DISCLOSURE_SCORE', 'Bloomberg ESG disclosure score',      false],
    ['ENVIRONMENTAL_SCORE',  'Environmental score',                 false],
    ['SOCIAL_SCORE',         'Social score',                        false],
    ['GOVERNANCE_SCORE',     'Governance score',                    false],
    ['CARBON_EMISSIONS_SCOPE1','Scope 1 carbon emissions',         false],
    ['CARBON_EMISSIONS_SCOPE2','Scope 2 carbon emissions',         false],
    ['GHG_INTENSITY_REVENUE', 'GHG intensity (per revenue)',        false],
  ]],
  // Volatility & Derivatives
  ['Volatility & Derivatives', [
    ['HIST_VOL_30D',       '30-day historical volatility',          true],
    ['HIST_VOL_60D',       '60-day historical volatility',          true],
    ['HIST_VOL_90D',       '90-day historical volatility',          true],
    ['30DAY_IMPVOL_100_PCT','30-day ATM implied vol (100%)',        false],
    ['3MTH_IMPVOL_100_PCT','3-month ATM implied vol (100%)',        false],
    ['OPT_CHAIN',          'Option chain (BDS array)',              true],
    ['OPT_EXPIRE_DT',      'Option expiry dates (BDS array)',       true],
  ]],
  // Reference / Metadata
  ['Reference & Metadata', [
    ['NAME',               'Security short name',                   true],
    ['SECURITY_DES',       'Security description',                  true],
    ['COMPANY_NAME',       'Company full name',                     true],
    ['GICS_SECTOR_NAME',   'GICS sector',                           true],
    ['GICS_INDUSTRY_NAME', 'GICS industry',                         true],
    ['EMPLOYEE_CNT',       'Employee count',                        true],
    ['CEO_NAME',           'CEO name',                              true],
    ['COUNTRY_ISO',        'Country ISO code',                      true],
    ['CRNCY',              'Currency',                              true],
    ['ID_ISIN',            'ISIN',                                  true],
    ['ID_CUSIP',           'CUSIP',                                 true],
    ['INDUSTRY_SECTOR',    'Bloomberg industry sector',             true],
  ]],
  // Bulk data (BDS)
  ['Bulk / Array (BDS)', [
    ['INDX_MEMBERS',       'Index constituent tickers',             true],
    ['INDX_MWEIGHT',       'Index constituent weights',             true],
    ['DVD_HIST_ALL',       'Dividend history',                      true],
    ['EARN_ANN_DT_AND_EPS','Earnings announcement dates + EPS',     true],
    ['BOARD_OF_DIRECTORS', 'Board of directors list',               true],
    ['FUND_SECTOR_WEIGHTS','ETF sector allocation',                 true],
    ['FUND_COUNTRY_WEIGHTS','ETF country allocation',               true],
    ['OPT_CHAIN',          'Options chain for a security',          true],
  ]],
  // BQL-only operational/KPI fields
  ['BQL — Operational / KPI (Excel only)', [
    ['NUMBER_OF_VEHICLES_SOLD',   'Vehicle deliveries (TSLA, etc.)',        false],
    ['RETAIL_SUBSCRIBERS',        'Paid retail subscribers',                 false],
    ['STREAMING_SUBSCRIBERS',     'Streaming subscribers (NFLX, DIS, etc.)',false],
    ['PAID_SUBSCRIBERS',          'Total paid subscribers',                  false],
    ['MONTHLY_ACTIVE_USERS',      'Monthly active users (MAU)',              false],
    ['DAILY_ACTIVE_USERS',        'Daily active users (DAU)',                false],
    ['AVERAGE_REVENUE_PER_USER',  'ARPU',                                    false],
    ['UNIT_SALES_IPHONE',         'iPhone units sold',                       false],
    ['UNIT_SALES_MAC',            'Mac units sold',                          false],
    ['UNIT_SALES_IPAD',           'iPad units sold',                         false],
    ['SAME_STORE_SALES_GROWTH',   'Comparable / same-store sales growth',    false],
    ['STORE_COUNT',               'Total store / location count',            false],
    ['ECOMMERCE_GMV',             'E-commerce gross merchandise value',      false],
    ['BACKLOG_UNITS',             'Order backlog in units',                  false],
    ['PROD_PRICE_AVG_US',         'Average selling price (US)',              false],
    ['RENEWAL_RATE',              'Contract / subscription renewal rate',    false],
    ['CHURN_RATE',                'Customer churn rate',                     false],
    ['PASSENGER_LOAD_FACTOR',     'Airline passenger load factor',           false],
    ['REVENUE_PASSENGER_MILES',   'Revenue passenger miles (airlines)',      false],
    ['AVAILABLE_SEAT_MILES',      'Available seat miles (airlines)',         false],
    ['HOTEL_OCCUPANCY_RATE',      'Hotel occupancy rate',                    false],
    ['REVPAR',                    'Revenue per available room (hotels)',     false],
    ['ADR_HOTEL',                 'Average daily rate (hotels)',             false],
    ['NET_NEW_UNITS',             'Net new unit openings (restaurants)',     false],
    ['SYSTEM_SALES',              'Systemwide sales (franchises)',           false],
    ['PRODUCTION_VOLUME',         'Production output volume',               false],
    ['SALES_VOLUME_BBL',          'Sales volume in barrels (energy)',        false],
    ['DRILLING_ACTIVITY',         'Active drilling rigs',                   false],
  ]],
];
